<Label>:
    color: 'black'

<Button>:
    color: (1, 1, 1, 1)
    background_normal: 'atlas://assets/audiochef_theme/button'
    background_color: app.main_color

<CheckBox>:
    background_radio_down: 'atlas://assets/audiochef_theme/checkbox_radio_on'
    background_radio_normal: 'atlas://assets/audiochef_theme/checkbox_radio_off'


<Popup>:
    title_color: (0., 0., 0., 1.)
    background: 'atlas://assets/audiochef_theme/modalview-background'
    background_color: app.window_background_color